# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kcJFkfT93Ip_qk7MnlMNhOz3zj2YTDkK
"""

import pandas as pd
df=pd.read_csv('sample_data/california_housing_test.csv')
df.head()

df.shape

df.dtypes

df.isnull()

df.isnull().sum()

df[df['median_income']<2]['median_house_value']

df.columns

df.columns[:2]

for i in df.columns[:2]:
  print (df[i])

df[((df['housing_median_age']<20) & (df['median_house_value']>70000))]

df[((df['housing_median_age']<20) & (df['median_house_value']>70000))]['population']

df.describe()

df['median_house_value'].min()

df['median_house_value'].max()

df[df['median_income']==3.1250]['median_house_value'].max()

df[df['median_house_value']==df['median_house_value'].min()]['population'].max()